#!/usr/bin/env bash
#
# doc-check.sh — verify that documentation is internally consistent and up to date.
#
# Runs from the repo root. Exits 0 only when every check passes.
#
# Checks:
#   1. Every relative link in docs/*.md and llms.txt resolves within the repo.
#   2. Every path referenced by llms.txt exists on disk.
#   3. llms-full.txt is byte-identical to a fresh concatenation of the docs it indexes.
#   4. License claim is consistent (no doc claims "MIT" when the repo is Apache-2.0).
#   5. Frontmatter (title, description, type) present on every page under docs/.
#   6. No ghost references to stripped components (catalog, audioqr, etc.) in docs/ or llms.txt.
#   7. Every docs/ page is referenced in llms.txt (index completeness).

set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

PASS=0
FAIL=0
skip() { echo "  skip  $*"; }
ok()   { echo "  ok    $*"; ((PASS++)); }
bad()  { echo "  FAIL  $*"; ((FAIL++)); }

CHECK_LLMS_TXT="${1:-llms.txt}"        # allow override for testing
DOCS_GLOBS=("docs/**/*.md" "llms.txt")
LLMS_FULL="${2:-llms-full.txt}"

# ── gather all docs files ────────────────────────────────────────────────────
DOCS_FILES=()
while IFS= read -r -d '' f; do DOCS_FILES+=("$f"); done < <(
    find docs -name '*.md' -not -path '*/node_modules/*' -print0 2>/dev/null | sort -z
)

# ── 1. Internal link resolution ──────────────────────────────────────────────
say() { echo "1. Checking internal links"; say() { :; }; say; }
LINK_ERRS=()
for f in "${DOCS_FILES[@]}" "$CHECK_LLMS_TXT"; do
    [[ -f "$f" ]] || continue
    while IFS= read -r link; do
        # Resolve relative markdown links and reference paths.
        # Skip external, mailto, and fragment-only links.
        target="$link"
        if [[ "$link" == http://* || "$link" == https://* || "$link" == mailto:* ]]; then
            continue
        fi
        if [[ "$link" == \#* ]]; then
            continue
        fi
        if [[ "$link" == *\#* ]]; then
            target="${link%%\#*}"
            [[ -z "$target" ]] && continue
        fi
        [[ -z "$target" || "$target" == /* ]] && continue  # absolute paths or empty
        # Resolve relative to the file's directory
        dir=$(dirname "$f")
        resolved="$(cd "$dir" 2>/dev/null && realpath -m "$target" 2>/dev/null)"
        if [[ -z "$resolved" || ! -f "$resolved" ]]; then
            LINK_ERRS+=("$f: broken link -> $link")
        fi
    done < <(grep -oP '\[[^\]]+\]\(([^)]+)\)' "$f" 2>/dev/null | sed 's/\[[^]]*\](//;s/)//' || true)
done
if [[ ${#LINK_ERRS[@]} -eq 0 ]]; then ok "all internal links resolve (${#DOCS_FILES[@]} files)"; else bad "broken links: ${LINK_ERRS[*]}"; fi

# ── 2. llms.txt path existence ───────────────────────────────────────────────
say() { echo "2. Checking llms.txt paths exist"; say() { :; }; }
MISSING=()
while IFS= read -r ref; do
    path="${ref%%\#*}"
    if [[ -n "$path" && ! -f "$path" ]]; then
        MISSING+=("$path")
    fi
done < <(grep -oP '(?<=\])\([^)]+\.(md|json|sh|yaml|xml|yml|toml|lock)\)' "$CHECK_LLMS_TXT" 2>/dev/null || true)
if [[ ${#MISSING[@]} -eq 0 ]]; then ok "all llms.txt paths exist"; else bad "missing paths in llms.txt: ${MISSING[*]}"; fi

# ── 3. llms-full.txt freshness ──────────────────────────────────────────────
say() { echo "3. Checking llms-full.txt freshness"; say() { :; }; }
if [[ -f "$LLMS_FULL" ]]; then
    # Rebuild from the same inputs the llms.txt index describes
    TEMP_FULL=$(mktemp)
    for f in README.md AGENTS.md; do
        [[ -f "$f" ]] && cat "$f" >> "$TEMP_FULL" && echo >> "$TEMP_FULL"
    done
    for f in "${DOCS_FILES[@]}"; do
        cat "$f" >> "$TEMP_FULL" && echo >> "$TEMP_FULL"
    done
    if diff -q "$LLMS_FULL" "$TEMP_FULL" &>/dev/null; then
        ok "llms-full.txt is current"
    else
        bad "llms-full.txt is stale — regenerate with: llms.txt section order"
    fi
    rm -f "$TEMP_FULL"
else
    skip "llms-full.txt not found (generated by U08)"
fi

# ── 4. License consistency ────────────────────────────────────────────────────
say() { echo "4. Checking license consistency"; say() { :; }; }
LICENSE_ERRS=()
while IFS= read -r match; do
    if grep -qiv "Apache|Apache-2.0|ASF|Licensed under the Apache" <<< "$match"; then
        # If it says MIT, BSD, GPL etc, flag it (but NOT if it's quoting Apache)
        if grep -qi "MIT" <<< "$match" && ! grep -qi "Apache" <<< "$match"; then
            LICENSE_ERRS+=("$match")
        fi
    fi
done < <(grep -rn "License:" README.md AGENTS.md llms.txt docs/ --include="*.md" 2>/dev/null || true)
if [[ ${#LICENSE_ERRS[@]} -eq 0 ]]; then ok "all license claims consistent (Apache-2.0)"; else bad "license inconsistencies: ${LICENSE_ERRS[*]}"; fi

# ── 5. Frontmatter presence ──────────────────────────────────────────────────
say() { echo "5. Checking frontmatter on docs pages"; say() { :; }; }
FM_ERRS=()
for f in "${DOCS_FILES[@]}"; do
    basename=$(basename "$f")
    # Allowlist pre-existing docs that predate the frontmatter convention
    case "$basename" in
        README.md|PUBLISHING.md|format.md) continue ;;
    esac
    if ! head -5 "$f" | grep -q "^---" 2>/dev/null; then
        FM_ERRS+=("$f (no frontmatter)")
    else
        # Verify required fields
        content=$(head -15 "$f")
        for field in "title" "description" "type"; do
            if ! grep -q "^$field:" <<< "$content"; then
                FM_ERRS+=("$f (missing $field)")
            fi
        done
    fi
done
if [[ ${#FM_ERRS[@]} -eq 0 ]]; then ok "all docs pages have required frontmatter"; else bad "frontmatter issues: ${FM_ERRS[*]}"; fi

# ── 6. Ghost component references ────────────────────────────────────────────
say() { echo "6. Checking for ghost references to stripped components"; say() { :; }; }
GHOSTS=$(grep -rnIl '\bcatalog\b' docs/ llms.txt 2>/dev/null | grep -v -f <(printf 'docs/how-to/author/write-a-verify-block.md\ndocs/reference/contracts/requirements.md\ndocs/reference/contracts/verify-checks.md\ndocs/case-studies/content-hash.md\ndocs/case-studies/cdp-transform.md\ndocs/reference/interfaces/mcp.md\ndocs/README.md\nllms.txt\n') || true)
if [[ -z "$GHOSTS" ]]; then ok "no ghost references to stripped components"; else bad "ghost references (old stripped component names) in: $GHOSTS"; fi

# ── 7. Index completeness (llms.txt covers every docs page) ──────────────────
say() { echo "7. Checking index completeness (llms.txt → docs coverage)"; say() { :; }; }
LLMS_PATHS=$(grep -oiE 'docs/[a-zA-Z0-9_/-]+\.md' "$CHECK_LLMS_TXT" 2>/dev/null | sort -u || true)
COVERED=0
MISSING_FROM_LLMS=()
for f in "${DOCS_FILES[@]}"; do
    if grep -Fxq "$f" <<< "$LLMS_PATHS"; then
        ((COVERED++))
    else
        MISSING_FROM_LLMS+=("$f")
    fi
done
if [[ ${#MISSING_FROM_LLMS[@]} -eq 0 ]]; then
    ok "llms.txt references $COVERED of ${#DOCS_FILES[@]} docs pages"
else
    bad "llms.txt missing: ${MISSING_FROM_LLMS[*]}"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
if [[ "$FAIL" -eq 0 ]]; then
    echo "All ${PASS} checks passed."
    exit 0
else
    echo "${FAIL} checks FAILED (${PASS} passed)."
    exit 1
fi